### Login Docente/Empleado
POST http://192.168.100.5:8087/api/Seguridad/Login HTTP/1.1
Content-Type: application/json

{
    "Usuario": "PEOR820306JX4",
    "Password": "Cobach123!"
}
###
POST http://192.168.100.5:8087/api/Seguridad/Login HTTP/1.1
Content-Type: application/json

{
    "Usuario": "LEAE741024QX0",
    "Password": "Cobach123!"
}

###
POST http://192.168.100.5:8087/api/Seguridad/Login HTTP/1.1
Content-Type: application/json

{
    "Usuario": "LEAE741024QX0",
    "Password": "Cobach123!"
}

###
POST http://192.168.100.5:8087/api/Seguridad/Login HTTP/1.1
Content-Type: application/json

{
    "Usuario": "MUMT741003QD9",
    "Password": "Cobach123!"
}

### Login Docente/Empleado
POST http://192.168.100.5:8087/api/Seguridad/Login HTTP/1.1
Content-Type: application/json

{
    "Usuario": "Rald880607hta",
    "Password": "Mia021224#"
}


###
POST http://192.168.100.5:8087/api/Seguridad/LoginAlumnos HTTP/1.1
Content-Type: application/json

{
    "Usuario":"LOML100201HCSPRSA2",
    "Password":"25A0710225M0074"
}
###
POST /api/Seguridad/ObtenerDatosPorCorreo?correo=rperez@cobach.edu.mx HTTP/1.1
Host: 192.168.100.5:8087
Accept: */*
Content-Length: 0


### 
POST /api/Seguridad/ObtenerDatosPorCorreo?correo=melissa.mendoza.2401370@cobach.edu.mx HTTP/1.1
Host: 192.168.100.5:8087
Accept: */*
Content-Length: 0

###

POST /api/Seguridad/ObtenerDatosPorCorreo?correo=carlos.ponce.25sea06@cobach.edu.mx HTTP/1.1
Host: 192.168.100.5:8087
Accept: */*
Content-Length: 0


### 
POST /api/Seguridad/ObtenerDatosPorCorreo?correo=carlo.ramirez.2021@cobach.edu.mx HTTP/1.1
Host: 192.168.100.5:8087
Accept: */*
Content-Length: 0

###
POST /api/Seguridad/ObtenerDatosPorCorreo?correo=camila.coutino.2403378@cobach.edu.mx HTTP/1.1
Host: 192.168.100.5:8087
Accept: */*
Content-Length: 0

###
POST /api/Seguridad/ObtenerDatosPorCorreo?correo=eleodoro.leon.agu@cobach.edu.mx HTTP/1.1
Host: 192.168.100.5:8087
Accept: */*
Content-Length: 0

###
POST /api/Seguridad/ObtenerDatosPorCorreo?correo=dramos@cobach.edu.mx HTTP/1.1
Host: 192.168.100.5:8087
Accept: */*
Content-Length: 0

###
POST /api/Seguridad/ObtenerDatosPorCorreo?correo=autenticacion@cobach.edu.mx HTTP/1.1
Host: 192.168.100.5:8087
Accept: */*
Content-Length: 0

###
POST /api/Seguridad/ObtenerDatosPorCorreo?correo=teresa.muoz.mor@cobach.edu.mx HTTP/1.1
Host: 192.168.100.5:8087
Accept: */*
Content-Length: 0

