### Login Docente/Empleado
POST http://192.168.100.5:8087/api/Seguridad/Login HTTP/1.1
Content-Type: application/json

{
    "Usuario": "PEOR820306JX4",
    "Password": "Cobach123!"
}

###

POST http://192.168.100.5:8087/api/Seguridad/LoginAlumnos HTTP/1.1
Content-Type: application/json

{
    "Usuario":"LOML100201HCSPRSA2",
    "Password":"25A0710225M0074"
}
