# Generated by Django 6.0.5 on 2026-06-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id_plantel', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Plantel',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id_conversacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='agenda.plantel')),
            ],
            options={
                'db_table': 'Conversacion',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_turno', models.CharField(max_length=30)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='agenda.plantel')),
            ],
            options={
                'db_table': 'Turno',
                'unique_together': {('plantel', 'nombre_turno')},
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.BigAutoField(primary_key=True, serialize=False)),
                ('letra', models.CharField(max_length=1)),
                ('semestre', models.IntegerField()),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='agenda.turno')),
            ],
            options={
                'db_table': 'Grupo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password_mock', models.CharField(blank=True, max_length=128, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('plantel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='agenda.plantel')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='agenda.rol')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='agenda.turno')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='PermisoEspecial',
            fields=[
                ('id_permiso_especial', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('turno_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_otorgados', to='agenda.turno')),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos_autorizados', to='agenda.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_especiales', to='agenda.usuario')),
            ],
            options={
                'db_table': 'PermisoEspecial',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('evento_creado', 'Evento creado'), ('evento_actualizado', 'Evento actualizado'), ('evento_eliminado', 'Evento eliminado'), ('recordatorio', 'Recordatorio')], max_length=30)),
                ('evento_titulo', models.CharField(max_length=200)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='agenda.usuario')),
            ],
            options={
                'db_table': 'Notificacion',
                'ordering': ['-leida', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenido_cifrado', models.TextField()),
                ('iv', models.CharField(max_length=24)),
                ('metadatos_cifrados', models.TextField(blank=True, null=True)),
                ('iv_metadatos', models.CharField(blank=True, max_length=24, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='agenda.conversacion')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='agenda.usuario')),
            ],
            options={
                'db_table': 'Mensaje',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='conversacion',
            name='participante_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_a', to='agenda.usuario'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='participante_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_b', to='agenda.usuario'),
        ),
        migrations.CreateModel(
            name='LecturaMensaje',
            fields=[
                ('id_lectura_mensaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='agenda.conversacion')),
                ('ultimo_leido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agenda.mensaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='agenda.usuario')),
            ],
            options={
                'db_table': 'LecturaMensaje',
                'unique_together': {('conversacion', 'usuario')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='conversacion',
            unique_together={('participante_a', 'participante_b')},
        ),
    ]
