# Generated by Django 6.0.5 on 2026-06-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_sesion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
