# Generated by Django 6.0.5 on 2026-06-14 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_usuario_nombre_usuario_password_mock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('participante_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_a', to='agenda.usuario')),
                ('participante_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_b', to='agenda.usuario')),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='agenda.plantel')),
            ],
            options={
                'db_table': 'Conversacion',
                'unique_together': {('participante_a', 'participante_b')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_cifrado', models.TextField()),
                ('iv', models.CharField(max_length=24)),
                ('metadatos_cifrados', models.TextField(blank=True, null=True)),
                ('iv_metadatos', models.CharField(blank=True, max_length=24, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='agenda.conversacion')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='agenda.usuario')),
            ],
            options={
                'db_table': 'Mensaje',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='LecturaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='agenda.conversacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='agenda.usuario')),
                ('ultimo_leido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agenda.mensaje')),
            ],
            options={
                'db_table': 'LecturaMensaje',
                'unique_together': {('conversacion', 'usuario')},
            },
        ),
    ]
