# Generated by Django 6.0.5 on 2026-06-15 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('evento_creado', 'Evento creado'), ('evento_actualizado', 'Evento actualizado'), ('evento_eliminado', 'Evento eliminado'), ('recordatorio', 'Recordatorio')], max_length=30)),
                ('evento_titulo', models.CharField(max_length=200)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='agenda.usuario')),
            ],
            options={
                'db_table': 'Notificacion',
                'ordering': ['-leida', '-fecha_creacion'],
            },
        ),
    ]
