# Generated by Django 6.0.5 on 2026-06-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_empleado',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('plantel', 'nombre_turno')},
        ),
    ]
