# Generated by Django 6.0.5 on 2026-06-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_solicitudadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='id',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_notificacion',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
