# Generated by Django 6.0.5 on 2026-06-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_remove_turno_plantel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='plantel',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='turno',
        ),
        migrations.CreateModel(
            name='UsuarioPlantel',
            fields=[
                ('id_usuario_plantel', models.BigAutoField(primary_key=True, serialize=False)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='agenda.plantel')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='agenda.turno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planteles_asignados', to='agenda.usuario')),
            ],
            options={
                'db_table': 'UsuarioPlantel',
                'unique_together': {('usuario', 'plantel', 'turno')},
            },
        ),
    ]
