# Generated by Django 6.0.5 on 2026-06-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_remove_usuario_plantel_remove_usuario_turno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id_calendario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('clave', models.CharField(max_length=30, unique=True)),
                ('ciclo', models.CharField(max_length=20)),
                ('es_publico', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Calendario',
                'ordering': ['orden', 'id_calendario'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=20)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'TipoEvento',
                'ordering': ['orden', 'id_tipo_evento'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, default='', max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, default='', max_length=150)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('grupo', models.CharField(blank=True, max_length=2, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.calendario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to='agenda.usuario')),
                ('plantel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.plantel')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.turno')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='agenda.tipoevento')),
            ],
            options={
                'db_table': 'Evento',
                'ordering': ['fecha_inicio', 'hora_inicio'],
            },
        ),
    ]
