# Generated by Django 6.0.5 on 2026-06-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_seed_calendarios_tipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoevento',
            name='clave',
        ),
    ]
