# Generated by Django 6.0.5 on 2026-06-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_remove_tipoevento_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(default='azul', max_length=20)),
                ('audiencia', models.CharField(choices=[('todos', 'Todos'), ('admin', 'Administrativo'), ('docente', 'Docentes'), ('alumno', 'Alumnos')], default='todos', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios_creados', to='agenda.usuario')),
                ('plantel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='agenda.plantel')),
            ],
            options={
                'db_table': 'Anuncio',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
