# Generated by Django 6.0.5 on 2026-06-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_seed_tipos_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoevento',
            options={'ordering': ['plantel', 'id_tipo_evento']},
        ),
    ]
