# Generated by Django 6.0.5 on 2026-06-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_anuncio'),
        ('agenda', '0019_alter_tipoevento_options'),
    ]

    operations = [
    ]
