# Generated by Django 6.0.5 on 2026-06-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_merge_0018_anuncio_0019_alter_tipoevento_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoFCM',
            fields=[
                ('id_dispositivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('rol', models.CharField(max_length=50)),
                ('token_fcm', models.CharField(max_length=255, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plantel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='agenda.plantel')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='agenda.usuario')),
            ],
            options={
                'db_table': 'DispositivoFCM',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
