# Generated by Django 6.0.5 on 2026-06-22 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_dispositivofcm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='evento_titulo',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='leida',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='audiencia',
            field=models.CharField(default='todos', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(choices=[('anuncio', 'Anuncio'), ('evento', 'Evento')], default='anuncio', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='plantel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='agenda.plantel'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='referencia_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(blank=True, default=''),
        ),
    ]
