# Generated by Django 6.0.5 on 2026-06-23 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0023_reordenar_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GoogleOauthCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_uri', models.CharField(default='https://oauth2.googleapis.com/token', max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.TextField()),
                ('expiry', models.DateTimeField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to='agenda.usuario')),
            ],
            options={
                'db_table': 'GoogleOauthCredential',
            },
        ),
    ]
