# Generated by Django 6.0.5 on 2026-06-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0024_google_calendar_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleoauthcredential',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='googleoauthcredential',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='googleoauthcredential',
            name='token_uri',
        ),
    ]
