# Generated by Django 6.0.5 on 2026-06-23 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0025_remove_redundant_oauth_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='google_event_id',
        ),
        migrations.CreateModel(
            name='EventoGoogleSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_syncs', to='agenda.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_event_syncs', to='agenda.usuario')),
            ],
            options={
                'db_table': 'EventoGoogleSync',
                'unique_together': {('evento', 'usuario')},
            },
        ),
    ]
