# Generated by Django 6.0.5 on 2026-06-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0028_delete_permisoespecial'),
        ('agenda', '0029_solicitudadmin_plantel_fk'),
    ]

    operations = [
    ]
