# Generated by Django 6.0.5 on 2026-06-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0030_merge_20260624_0936'),
        ('agenda', '0030_remove_dispositivofcm_id_externo_and_more'),
    ]

    operations = [
    ]
