# Generated by Django 6.0.5 on 2026-06-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0034_plantel_uniqueidentifier_field'),
        ('agenda', '0034_semestre_letra_grupo_evento'),
    ]

    operations = [
    ]
