# Generated by Django 6.0.5 on 2026-06-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0036_anuncio_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='agenda.turno'),
        ),
    ]
