# Generated by Django 6.0.5 on 2026-07-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0038_google_credential_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivofcm',
            name='temas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
