# Generated by Django 6.0.5 on 2026-07-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0039_dispositivofcm_temas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivofcm',
            name='plantel',
        ),
    ]
