# Generated by Django 6.0.5 on 2026-07-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0042_reiniciar_asignaciones_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='audiencia',
            field=models.CharField(choices=[('todos', 'Todos'), ('colaborador', 'Colaboradores'), ('admin', 'Administrativo'), ('docente', 'Docentes'), ('alumno', 'Alumnos')], default='todos', max_length=20),
        ),
    ]
