# Generated by Django 6.0.5 on 2026-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0043_alter_anuncio_audiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadmin',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('visualizacion', 'Visualizar plantel'), ('turno', 'Cambio de turno')], default='admin', max_length=20),
        ),
    ]
