# Generated by Django 6.0.5 on 2026-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0044_solicitudadmin_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadmin',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('revocada', 'Revocada')], default='pendiente', max_length=20),
        ),
    ]
