# Generated by Django 6.0.5 on 2026-07-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0045_alter_solicitudadmin_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.BigIntegerField(blank=True, null=True)),
                ('usuario_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario_correo', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_rol', models.CharField(blank=True, max_length=50, null=True)),
                ('accion', models.CharField(max_length=20)),
                ('entidad_tipo', models.CharField(max_length=50)),
                ('entidad_id', models.CharField(blank=True, max_length=100, null=True)),
                ('datos_previos', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AuditoriaLog',
                'indexes': [models.Index(fields=['fecha_hora'], name='AuditoriaLo_fecha_h_7307fd_idx'), models.Index(fields=['usuario_id'], name='AuditoriaLo_usuario_f08378_idx'), models.Index(fields=['entidad_tipo'], name='AuditoriaLo_entidad_d7068b_idx')],
            },
        ),
    ]
