# Generated by Django 6.0.5 on 2026-07-21 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0046_auditorialog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrupacion',
            fields=[
                ('id_agrupacion', models.UUIDField(db_column='id_agrupacion', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Agrupacion',
            },
        ),
        migrations.AddField(
            model_name='plantel',
            name='agrupacion',
            field=models.ForeignKey(blank=True, db_column='agrupacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planteles', to='agenda.agrupacion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='agrupacion',
            field=models.ForeignKey(blank=True, db_column='agrupacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='agenda.agrupacion'),
        ),
    ]
