# Generated by Django 6.0.5 on 2026-07-21 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0047_agrupacion_plantel_agrupacion_usuario_agrupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrupacion',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subagrupaciones', to='agenda.agrupacion'),
        ),
    ]
