# Generated by Django 6.0.5 on 2026-07-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0048_agrupacion_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='agenda.usuario'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(choices=[('anuncio', 'Anuncio'), ('evento', 'Evento'), ('cuenta', 'Cuenta'), ('mensaje', 'Mensaje'), ('solicitud', 'Solicitud')], default='anuncio', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['destinatario', 'leido'], name='Notificacio_destina_706e53_idx'),
        ),
    ]
