# Generated by Django 6.0.5 on 2026-07-21 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0049_seed_roles_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoevento',
            options={'ordering': ['plantel', 'agrupacion', 'id_tipo_evento']},
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='agrupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_evento', to='agenda.agrupacion'),
        ),
    ]
