# Generated by Django 6.0.5 on 2026-07-21 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0050_alter_tipoevento_options_tipoevento_agrupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='agrupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.agrupacion'),
        ),
    ]
