# Generated by Django 6.0.5 on 2026-07-22 00:14

import uuid

import agenda.fields
from django.db import migrations


FORWARD_SQL = """
-- 1. Drop FK constraints que referencian Agrupacion
DECLARE @sql NVARCHAR(MAX) = '';
SELECT @sql += 'ALTER TABLE [' + OBJECT_SCHEMA_NAME(parent_object_id) + '].[' + OBJECT_NAME(parent_object_id) + '] DROP CONSTRAINT [' + name + '];' + CHAR(13)
FROM sys.foreign_keys
WHERE referenced_object_id = OBJECT_ID('Agrupacion');
EXEC sp_executesql @sql;

-- 2. Drop PK constraint
DECLARE @pk_name NVARCHAR(200);
SELECT @pk_name = name FROM sys.key_constraints WHERE type = 'PK' AND parent_object_id = OBJECT_ID('Agrupacion');
IF @pk_name IS NOT NULL EXEC('ALTER TABLE [dbo].[Agrupacion] DROP CONSTRAINT [' + @pk_name + ']');

-- 3. Drop indexes on FK columns (prevent ALTER COLUMN)
DROP INDEX IF EXISTS [Agrupacion_parent_id_adcad817] ON [dbo].[Agrupacion];
DROP INDEX IF EXISTS [Plantel_agrupacion_id_14a31067] ON [dbo].[Plantel];
DROP INDEX IF EXISTS [Usuario_agrupacion_id_8b9098cc] ON [dbo].[Usuario];
DROP INDEX IF EXISTS [TipoEvento_agrupacion_id_1be6fb16] ON [dbo].[TipoEvento];
DROP INDEX IF EXISTS [Evento_agrupacion_id_3b693831] ON [dbo].[Evento];

-- 4. NULL referencias
UPDATE [dbo].[Plantel] SET [agrupacion_id] = NULL WHERE [agrupacion_id] IS NOT NULL;
UPDATE [dbo].[Usuario] SET [agrupacion_id] = NULL WHERE [agrupacion_id] IS NOT NULL;
UPDATE [dbo].[TipoEvento] SET [agrupacion_id] = NULL WHERE [agrupacion_id] IS NOT NULL;
UPDATE [dbo].[Evento] SET [agrupacion_id] = NULL WHERE [agrupacion_id] IS NOT NULL;
UPDATE [dbo].[Agrupacion] SET [parent_id] = NULL WHERE [parent_id] IS NOT NULL;

-- 5. DELETE toda la tabla
DELETE FROM [dbo].[Agrupacion];

-- 6. ALTER COLUMNs a uniqueidentifier
ALTER TABLE [dbo].[Agrupacion] ALTER COLUMN [id_agrupacion] uniqueidentifier NOT NULL;
ALTER TABLE [dbo].[Agrupacion] ALTER COLUMN [parent_id] uniqueidentifier NULL;
ALTER TABLE [dbo].[Plantel] ALTER COLUMN [agrupacion_id] uniqueidentifier NULL;
ALTER TABLE [dbo].[Usuario] ALTER COLUMN [agrupacion_id] uniqueidentifier NULL;
ALTER TABLE [dbo].[TipoEvento] ALTER COLUMN [agrupacion_id] uniqueidentifier NULL;
ALTER TABLE [dbo].[Evento] ALTER COLUMN [agrupacion_id] uniqueidentifier NULL;

-- 7. Re-crear PK
ALTER TABLE [dbo].[Agrupacion] ADD CONSTRAINT [PK_Agrupacion] PRIMARY KEY CLUSTERED ([id_agrupacion]);

-- 8. Re-crear indexes
SET QUOTED_IDENTIFIER ON;
CREATE INDEX [IX_Agrupacion_parent_id] ON [dbo].[Agrupacion]([parent_id]) WHERE [parent_id] IS NOT NULL;
CREATE INDEX [IX_Plantel_agrupacion_id] ON [dbo].[Plantel]([agrupacion_id]) WHERE [agrupacion_id] IS NOT NULL;
CREATE INDEX [IX_Usuario_agrupacion_id] ON [dbo].[Usuario]([agrupacion_id]) WHERE [agrupacion_id] IS NOT NULL;
CREATE INDEX [IX_TipoEvento_agrupacion_id] ON [dbo].[TipoEvento]([agrupacion_id]) WHERE [agrupacion_id] IS NOT NULL;
CREATE INDEX [IX_Evento_agrupacion_id] ON [dbo].[Evento]([agrupacion_id]) WHERE [agrupacion_id] IS NOT NULL;

-- 9. INSERT direcciones (Nivel 1)
INSERT INTO [dbo].[Agrupacion] ([id_agrupacion], [nombre], [parent_id])
VALUES
('88b98c08-22b4-4123-948f-edb070931eb0', 'Direccion de Control y Seguimiento Normativo', NULL),
('79b6b28f-cbec-44a2-8e71-4e6ea5ae66d1', 'Direccion Academica', NULL),
('8db33926-f478-4085-afb2-3b22b4c00487', 'Direccion Juridica', NULL),
('4b680d3b-559d-409d-8cc1-57c00a89fd6e', 'Direccion de Vinculacion', NULL),
('20fe8de9-1ec1-4fdb-9c48-0203306c20a5', 'Direccion de Planeacion y Evaluacion Institucional', NULL),
('17dcf80b-af09-48af-b738-d9f834c0086e', 'Direccion de Administracion y Finanzas', NULL),
('618a6876-5ebf-40dd-8ed5-fc482fb589fe', 'Direccion de Tecnologias e Innovacion Educativa', NULL);

-- 10. INSERT subdirecciones (Nivel 2)
INSERT INTO [dbo].[Agrupacion] ([id_agrupacion], [nombre], [parent_id])
VALUES
('1adca72a-c251-473b-91ff-c5808df256a9', 'Subdireccion de Procesos de Evaluacion Academica', '79b6b28f-cbec-44a2-8e71-4e6ea5ae66d1'),
('615e6a6c-efb2-48e4-a0d8-98e5a159cf40', 'Subdireccion de Servicios Educativos', '79b6b28f-cbec-44a2-8e71-4e6ea5ae66d1'),
('6a3a8b21-76e9-4611-b138-31d1082603c4', 'Subdireccion de Bachillerato Mixto y Autoplaneado', '79b6b28f-cbec-44a2-8e71-4e6ea5ae66d1'),
('455b9788-09f3-4a3f-ab44-56d30d33dea7', 'Subdireccion de Desarrollo Academico', '79b6b28f-cbec-44a2-8e71-4e6ea5ae66d1'),
('c166c882-618f-487f-a5b9-a933449753d2', 'Subdireccion Juridica', '8db33926-f478-4085-afb2-3b22b4c00487'),
('ec10c60a-f13b-41d9-a7d6-aa55a65a775c', 'Subdireccion de Planeacion', '20fe8de9-1ec1-4fdb-9c48-0203306c20a5'),
('d9cf8153-09af-403f-9cd8-e93b35755a4e', 'Subdireccion de Operacion Administrativa y Financiera', '17dcf80b-af09-48af-b738-d9f834c0086e');

-- 11. Vincular Plantel a su agrupacion
UPDATE [dbo].[Plantel] SET [agrupacion_id] = '88b98c08-22b4-4123-948f-edb070931eb0'
WHERE [id_plantel] IN ('86cad435-cb4c-47d6-9a88-c053c2c10356', '80f2a0d3-e11a-40cb-a11d-43789e938fe1');

UPDATE [dbo].[Plantel] SET [agrupacion_id] = '1adca72a-c251-473b-91ff-c5808df256a9'
WHERE [id_plantel] IN ('336d014a-5d10-4a64-b082-4f2a76395401', '740878a1-c43f-4ff3-882f-736c32471f6b', 'c7a7d6de-91e3-4b76-b5cc-9da0d03319f0');

UPDATE [dbo].[Plantel] SET [agrupacion_id] = '615e6a6c-efb2-48e4-a0d8-98e5a159cf40'
WHERE [id_plantel] IN ('3cab38f1-2f0f-44a5-bcc0-f530cfa14b70', 'b3de5540-02f2-4358-a783-5baa24a36b6c', '3c01f02e-9503-4841-aa14-85c46eb5e919', 'b559a1fe-7cf2-4b0a-a3e4-6d183fade823');

UPDATE [dbo].[Plantel] SET [agrupacion_id] = '6a3a8b21-76e9-4611-b138-31d1082603c4'
WHERE [id_plantel] IN ('60df9b19-91db-4014-b84e-7fecbc0b26e3', '495ec924-2f66-4f15-85a8-60589dcd8eda', 'a6bc1bb3-18d1-41c3-9b61-2d89e606d671');

UPDATE [dbo].[Plantel] SET [agrupacion_id] = '455b9788-09f3-4a3f-ab44-56d30d33dea7'
WHERE [id_plantel] IN ('c9c734f1-7a4a-4d44-8be0-42e8aaba5fb7', '2ca91aef-5068-4f2e-9973-72f03aff6fb5', '42fc9e24-f2c7-4f54-9247-f248a5c737b7');

UPDATE [dbo].[Plantel] SET [agrupacion_id] = 'c166c882-618f-487f-a5b9-a933449753d2'
WHERE [id_plantel] IN ('7fc3bc0b-98d2-4de9-b8fd-88e762a5e444', '899ad006-8a67-4367-a9c4-531eee3be537');

UPDATE [dbo].[Plantel] SET [agrupacion_id] = '4b680d3b-559d-409d-8cc1-57c00a89fd6e'
WHERE [id_plantel] IN ('0b986693-e234-4bc5-b72b-ea1bb804cbcc', 'ce9d991c-8514-44b2-97c9-79555f6e3959');

UPDATE [dbo].[Plantel] SET [agrupacion_id] = 'ec10c60a-f13b-41d9-a7d6-aa55a65a775c'
WHERE [id_plantel] IN ('388c789d-b423-4c81-9711-484db86b353e', '1d38def0-f1cc-445a-9ab0-fcb8af56f1a5', '676ba9b3-87b1-483f-ac18-8a74cb6d4da3');

UPDATE [dbo].[Plantel] SET [agrupacion_id] = 'd9cf8153-09af-403f-9cd8-e93b35755a4e'
WHERE [id_plantel] IN ('98ccb8a5-9fa2-4584-ad6a-441710fecbee', '45e08ae6-be2a-4ea2-92f3-adaad89f5d3d', 'c8942981-ede1-4bd9-b6b4-14fa2e04f4ea', '8f55ccbc-11fb-4dca-a1b4-e4426ea20fe4', '22baff99-cec3-4c30-88a9-d95ca8dad9a2', '52661a99-bdd3-47c1-a6b9-999d74ab566f', '6bd72161-1889-45fe-af90-a7d80450654a', '0a160e01-0fef-421b-9128-243b13580a6a');

UPDATE [dbo].[Plantel] SET [agrupacion_id] = '618a6876-5ebf-40dd-8ed5-fc482fb589fe'
WHERE [id_plantel] IN ('6b53cff4-1f05-43b1-92a4-6fb6c0e6661d', 'd7d72d22-296a-4822-bac9-31f9df365db9', '33fc4145-3dae-4330-b683-90744692a0e2', '07085082-2881-4983-bbcc-089ba4aa0be2');

-- 12. Re-crear FKs
ALTER TABLE [dbo].[Plantel]   ADD CONSTRAINT [FK_Plantel_Agrupacion]   FOREIGN KEY ([agrupacion_id]) REFERENCES [dbo].[Agrupacion]([id_agrupacion]) ON DELETE SET NULL;
ALTER TABLE [dbo].[Usuario]   ADD CONSTRAINT [FK_Usuario_Agrupacion]   FOREIGN KEY ([agrupacion_id]) REFERENCES [dbo].[Agrupacion]([id_agrupacion]) ON DELETE SET NULL;
ALTER TABLE [dbo].[TipoEvento] ADD CONSTRAINT [FK_TipoEvento_Agrupacion] FOREIGN KEY ([agrupacion_id]) REFERENCES [dbo].[Agrupacion]([id_agrupacion]) ON DELETE CASCADE;
ALTER TABLE [dbo].[Evento]    ADD CONSTRAINT [FK_Evento_Agrupacion]    FOREIGN KEY ([agrupacion_id]) REFERENCES [dbo].[Agrupacion]([id_agrupacion]) ON DELETE CASCADE;
ALTER TABLE [dbo].[Agrupacion] ADD CONSTRAINT [FK_Agrupacion_Parent]   FOREIGN KEY ([parent_id])     REFERENCES [dbo].[Agrupacion]([id_agrupacion]) ON DELETE NO ACTION;
"""

REVERSE_SQL = """
-- 1. Drop explicit FK constraints
IF OBJECT_ID('FK_Plantel_Agrupacion', 'F') IS NOT NULL ALTER TABLE [dbo].[Plantel] DROP CONSTRAINT [FK_Plantel_Agrupacion];
IF OBJECT_ID('FK_Usuario_Agrupacion', 'F') IS NOT NULL ALTER TABLE [dbo].[Usuario] DROP CONSTRAINT [FK_Usuario_Agrupacion];
IF OBJECT_ID('FK_TipoEvento_Agrupacion', 'F') IS NOT NULL ALTER TABLE [dbo].[TipoEvento] DROP CONSTRAINT [FK_TipoEvento_Agrupacion];
IF OBJECT_ID('FK_Evento_Agrupacion', 'F') IS NOT NULL ALTER TABLE [dbo].[Evento] DROP CONSTRAINT [FK_Evento_Agrupacion];
IF OBJECT_ID('FK_Agrupacion_Parent', 'F') IS NOT NULL ALTER TABLE [dbo].[Agrupacion] DROP CONSTRAINT [FK_Agrupacion_Parent];

-- 2. Drop PK constraint
DECLARE @pk_name NVARCHAR(200);
SELECT @pk_name = name FROM sys.key_constraints WHERE type = 'PK' AND parent_object_id = OBJECT_ID('Agrupacion');
IF @pk_name IS NOT NULL EXEC('ALTER TABLE [dbo].[Agrupacion] DROP CONSTRAINT [' + @pk_name + ']');

-- 3. Drop indexes
DROP INDEX IF EXISTS [IX_Agrupacion_parent_id] ON [dbo].[Agrupacion];
DROP INDEX IF EXISTS [IX_Plantel_agrupacion_id] ON [dbo].[Plantel];
DROP INDEX IF EXISTS [IX_Usuario_agrupacion_id] ON [dbo].[Usuario];
DROP INDEX IF EXISTS [IX_TipoEvento_agrupacion_id] ON [dbo].[TipoEvento];
DROP INDEX IF EXISTS [IX_Evento_agrupacion_id] ON [dbo].[Evento];

-- 4. DELETE all rows
DELETE FROM [dbo].[Agrupacion];

-- 5. ALTER COLUMNs back to char(32)
ALTER TABLE [dbo].[Agrupacion] ALTER COLUMN [id_agrupacion] char(32) NOT NULL;
ALTER TABLE [dbo].[Agrupacion] ALTER COLUMN [parent_id] char(32) NULL;
ALTER TABLE [dbo].[Plantel] ALTER COLUMN [agrupacion_id] char(32) NULL;
ALTER TABLE [dbo].[Usuario] ALTER COLUMN [agrupacion_id] char(32) NULL;
ALTER TABLE [dbo].[TipoEvento] ALTER COLUMN [agrupacion_id] char(32) NULL;
ALTER TABLE [dbo].[Evento] ALTER COLUMN [agrupacion_id] char(32) NULL;

-- 6. Re-crear PK
ALTER TABLE [dbo].[Agrupacion] ADD CONSTRAINT [PK_Agrupacion] PRIMARY KEY CLUSTERED ([id_agrupacion]);

-- 7. Re-crear indexes (non-filtered to avoid QUOTED_IDENTIFIER issues)
CREATE INDEX [IX_Agrupacion_parent_id] ON [dbo].[Agrupacion]([parent_id]);
CREATE INDEX [IX_Plantel_agrupacion_id] ON [dbo].[Plantel]([agrupacion_id]);
CREATE INDEX [IX_Usuario_agrupacion_id] ON [dbo].[Usuario]([agrupacion_id]);
CREATE INDEX [IX_TipoEvento_agrupacion_id] ON [dbo].[TipoEvento]([agrupacion_id]);
CREATE INDEX [IX_Evento_agrupacion_id] ON [dbo].[Evento]([agrupacion_id]);

-- 8. Re-crear FKs
ALTER TABLE [dbo].[Plantel]   ADD CONSTRAINT [FK_Plantel_Agrupacion]   FOREIGN KEY ([agrupacion_id]) REFERENCES [dbo].[Agrupacion]([id_agrupacion]) ON DELETE SET NULL;
ALTER TABLE [dbo].[Usuario]   ADD CONSTRAINT [FK_Usuario_Agrupacion]   FOREIGN KEY ([agrupacion_id]) REFERENCES [dbo].[Agrupacion]([id_agrupacion]) ON DELETE SET NULL;
ALTER TABLE [dbo].[TipoEvento] ADD CONSTRAINT [FK_TipoEvento_Agrupacion] FOREIGN KEY ([agrupacion_id]) REFERENCES [dbo].[Agrupacion]([id_agrupacion]) ON DELETE CASCADE;
ALTER TABLE [dbo].[Evento]    ADD CONSTRAINT [FK_Evento_Agrupacion]    FOREIGN KEY ([agrupacion_id]) REFERENCES [dbo].[Agrupacion]([id_agrupacion]) ON DELETE CASCADE;
ALTER TABLE [dbo].[Agrupacion] ADD CONSTRAINT [FK_Agrupacion_Parent]   FOREIGN KEY ([parent_id])     REFERENCES [dbo].[Agrupacion]([id_agrupacion]) ON DELETE NO ACTION;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0051_evento_agrupacion'),
    ]

    operations = [
        migrations.RunSQL(
            sql=FORWARD_SQL,
            reverse_sql=REVERSE_SQL,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='agrupacion',
                    name='id_agrupacion',
                    field=agenda.fields.UniqueIdentifierField(
                        default=uuid.uuid4, editable=False,
                        primary_key=True, serialize=False
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
