# Generated by Django 6.0.5 on 2026-07-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0049_notificacion_destinatario_notificacion_leido_and_more'),
        ('agenda', '0052_alter_agrupacion_id_agrupacion'),
    ]

    operations = [
    ]
