# Generated by Django 6.0.5 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0053_merge_20260722_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantel',
            name='clave_tipo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
