# Generated by Django 6.0.5 on 2026-07-24 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0054_plantel_clave_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='agrupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.agrupacion'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='agrupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.agrupacion'),
        ),
    ]
